version: "3"
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
    - 2181:2181
  kafka:
    build: ./kafka
    ports:
    - 19092:19092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
    - zookeeper
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
    - "6123"
    ports:
    - 8081:8081
    command: jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ..:/code
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
    - "6121"
    - "6122"
    depends_on:
    - jobmanager
    command: taskmanager
    links:
    - jobmanager:jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
