version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.13
    restart: always
    ports:
    - 2181:2181
  kafka:
    build: ./kafka
    ports:
    - 19092:19092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
    - zookeeper
    volumes:
    - ..:/code
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink:1.7.0-scala_2.12}
    expose:
    - "6123"
    ports:
    - 8081:8081
    command: jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
    - ..:/code
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink:1.7.0-scala_2.12}
    expose:
    - "6121"
    - "6122"
    depends_on:
    - jobmanager
    command: taskmanager
    links:
    - jobmanager:jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
    - 5000:5000
    - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    depends_on:
    - elasticsearch
    - kafka
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
    - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
